# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "nvme" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-4bcd453f-15c3-4a65-a226-f0e80607f9bd";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-4bcd453f-15c3-4a65-a226-f0e80607f9bd".device = "/dev/disk/by-uuid/4bcd453f-15c3-4a65-a226-f0e80607f9bd";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/0BFC-887A";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/4f044e66-d562-4fff-a7d4-c1ad92326392"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
