# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "nvme" "usb_storage" "usbhid" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-b1558a93-37d7-4e22-b73b-c828ed778fe1";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-b1558a93-37d7-4e22-b73b-c828ed778fe1".device = "/dev/disk/by-uuid/b1558a93-37d7-4e22-b73b-c828ed778fe1";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/93CD-6996";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  fileSystems."/mnt/games" =
    { device = "/dev/disk/by-uuid/383349db-d73e-42ba-a848-d34c569379a5";
      fsType = "ext4";
    };

  fileSystems."/mnt/sdb1" =
    { device = "/dev/disk/by-uuid/f4f55898-26a3-4ec6-9fef-74504d3eba6d";
      fsType = "ext4";
    };

  fileSystems."/mnt/storage" =
    { device = "/dev/disk/by-uuid/df489494-bf49-4ef5-baf2-b0a062dd5687";
      fsType = "ext4";
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/997625ff-30d0-4d6b-ae35-4e68627c570d"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
