general {
    no_fade_in = false
    grace = 0
    disable_loading_bar = true
    hide_cursor = true
}

background {
    monitor =
    path = screenshot
    blur_passes = 2
    contrast = 1
    brightness = 0.5
    vibrancy = 0.2
    vibrancy_darkness = 0.2
}

# =========================
# Password
# =========================

input-field {
    monitor =

    size = 240, 52
    outline_thickness = 0
    rounding = 12

    inner_color = rgba(31, 31, 31, 0.90)
    font_color = rgba(212, 212, 212, 1.0)

    # No colorful authentication ring
    check_color = rgba(86, 156, 214, 1.0)
    fail_color = rgba(244, 71, 71, 1.0)
    capslock_color = -1
    numlock_color = -1
    bothlock_color = -1

    dots_size = 0.30
    dots_spacing = 0.15
    dots_center = true
    dots_rounding = -2

    fade_on_empty = true
    fade_timeout = 1000

    placeholder_text = <i>Password</i>
    hide_input = false

    position = 0, -20
    halign = center
    valign = center
}

# =========================
# Clock
# =========================

label {
    monitor =
    text = $TIME

    color = rgba(212, 212, 212, 1.0)
    font_size = 64
    font_family = JetBrainsMono Nerd Font

    position = 0, 75
    halign = center
    valign = center
    text_align = center
}

# =========================
# Date
# =========================

label {
    monitor =
    text = cmd[update:60000] date '+%A, %d %B'

    color = rgba(166, 173, 200, 0.85)
    font_size = 18
    font_family = JetBrainsMono Nerd Font

    position = 0, 20
    halign = center
    valign = center
    text_align = center
}
