background = 0xFF1F1F1F
base = 0xFF252525
text = 0xFFD4D4D4
alternate_base = 0xFF3A3A3A
bright_text = 0xFFFFFFFF

accent = 0xFFD4D4D4
accent_secondary = 0xFF888888

font_size = 11
small_font_size = 10

font_family = Sans Serif
font_family_monospace = monospace

rounding_large = 8
rounding_small = 4
